---
title: Promise中的then第二个参数和catch有什么区别
sidebar: auto
date: 2021-08-08 00:00:00
tags: 
  - 面试
categories: 
  - 面试
permalink: /pages/c949f76a9d7a5/
---

- 第一，reject是用来抛出异常的，catch是用来处理异常的；
- 第二：reject是Promise的方法，而then和catch是Promise实例的方法（Promise.prototype.then 和 Promise.prototype.catch）。

## 区别
- 1.如果在then的第一个函数里抛出了异常，后面的catch能捕获到，而then的第二个函数捕获不到
- 2.then的第二个参数和catch捕获错误信息的时候会就近原则，如果是promise内部报错，reject抛出错误后，then的第二个参数和catch方法都存在的情况下，只有then的第二个参数能捕获到，如果then的第二个参数不存在，则catch方法会捕获到

```
// bad
promise
  .then(function(data) {
    // success
  }, function(err) {
    // error
  });

// good
promise
  .then(function(data) { //cb
    // success
  })
  .catch(function(err) {
    // error
  });
```
上面代码中，第二种写法要好于第一种写法，理由是第二种写法可以捕获前面then方法执行中的错误，也更接近同步的写法（try/catch）。因此，建议总是使用catch方法，而不使用then方法的第二个参数

